version: '3'

# docker-compose up --build
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '4201:4200'
      - '49153:49153'
    volumes:
      - .:/usr/src/app/
      - "/usr/src/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=dev
